const mongoose=require('mongoose');
const softDelete={isDeleted:{type:Boolean,default:false,index:true},deletedAt:Date};

const imageSchema=new mongoose.Schema({secure_url:String,public_id:String,alt:String,order:{type:Number,default:0},isPrimary:{type:Boolean,default:false}},{_id:false});
const productSchema=new mongoose.Schema({name:{type:String,required:true,trim:true},slug:{type:String,required:true,unique:true,index:true},shortDescription:String,description:String,category:{type:mongoose.Schema.Types.ObjectId,ref:'Category',required:true,index:true},categorySlug:{type:String,index:true},bodyPart:{type:String,index:true},painArea:{type:String,index:true},activity:[{type:String,index:true}],sizes:[String],brand:{type:String,index:true},sku:{type:String,required:true,unique:true,index:true},tags:[String],seo:{title:String,description:String,keywords:[String]},specifications:[{name:String,value:String}],benefits:[String],ingredients:[String],careInstructions:[String],faqs:[{q:String,a:String}],dimensions:{length:Number,width:Number,height:Number,unit:{type:String,default:'cm'}},weight:{value:Number,unit:{type:String,default:'g'}},warranty:String,returns:String,shipping:String,gst:{type:Number,default:5},mrp:{type:Number,required:true,min:0},sellingPrice:{type:Number,required:true,min:0},discount:{type:Number,default:0},stock:{type:Number,default:0,index:true},lowStockThreshold:{type:Number,default:5},visibility:{type:String,enum:['public','private','draft'],default:'public',index:true},enabled:{type:Boolean,default:true,index:true},searchKeywords:[String],images:[imageSchema],relatedProducts:[{type:mongoose.Schema.Types.ObjectId,ref:'Product'}],isFeatured:{type:Boolean,default:false,index:true},isTrending:{type:Boolean,default:false,index:true},isBestSeller:{type:Boolean,default:false,index:true},isNewArrival:{type:Boolean,default:false,index:true},soldCount:{type:Number,default:0,index:true},ratingAverage:{type:Number,default:0},ratingCount:{type:Number,default:0},...softDelete},{timestamps:true,toJSON:{virtuals:true},toObject:{virtuals:true}});
productSchema.virtual('price').get(function(){return this.mrp});
productSchema.virtual('discountPrice').get(function(){return this.sellingPrice});
productSchema.virtual('bestSeller').get(function(){return this.isBestSeller});
productSchema.virtual('newArrival').get(function(){return this.isNewArrival});
productSchema.virtual('rating').get(function(){return this.ratingAverage});
productSchema.virtual('reviewCount').get(function(){return this.ratingCount});
productSchema.virtual('inStock').get(function(){return this.stock>0}); productSchema.index({name:'text',shortDescription:'text',description:'text',brand:'text',tags:'text',searchKeywords:'text'}); module.exports=mongoose.model('Product',productSchema);
