const crypto=require('crypto'); const {v4:uuid}=require('uuid'); const User=require('../models/User'); const AppError=require('../utils/AppError'); const {signAccessToken,signRefreshToken,verifyRefreshToken}=require('../utils/tokens'); const {transporter}=require('../config/mailer');
const sha=t=>crypto.createHash('sha256').update(t).digest('hex'); const otp=()=>String(Math.floor(100000+Math.random()*900000));
async function issue(user,remember=false){const jti=uuid(); const accessToken=signAccessToken(user); const refreshToken=signRefreshToken(user,jti); const days=remember?60:30; user.refreshTokens.push({jti,tokenHash:sha(refreshToken),expiresAt:new Date(Date.now()+days*864e5)}); user.lastLoginAt=new Date(); await user.save(); return {accessToken,refreshToken,user:safeUser(user)} }
function safeUser(u){const o=u.toObject?u.toObject():u; delete o.password; delete o.refreshTokens; delete o.resetPasswordOtp; delete o.emailVerificationOtp; return o;}
exports.register=async(data)=>{const code=otp(); const user=await User.create({...data,emailVerificationOtp:code,emailVerificationExpires:new Date(Date.now()+10*60e3)}); await sendMail(user.email,'Verify Aligno email',`Your Aligno Health Hub OTP is ${code}`); return issue(user,false)};
exports.login=async({email,password,rememberMe})=>{const user=await User.findOne({email:email?.toLowerCase(),isDeleted:false}).select('+password'); if(!user||!(await user.comparePassword(password))) throw new AppError('Invalid email or password',401); if(user.isBlocked||!user.isActive) throw new AppError('Account is blocked or inactive',403); return issue(user,!!rememberMe)};
exports.refresh=async(token)=>{const d=verifyRefreshToken(token); const user=await User.findById(d.id); if(!user) throw new AppError('Invalid refresh token',401); const found=user.refreshTokens.find(t=>t.jti===d.jti&&t.tokenHash===sha(token)&&t.expiresAt>new Date()); if(!found) throw new AppError('Refresh token expired',401); user.refreshTokens=user.refreshTokens.filter(t=>t.jti!==d.jti); await user.save(); return issue(user,true)};
exports.logout=async(userId,token)=>{if(userId){const user=await User.findById(userId); if(user&&token){const d=verifyRefreshToken(token); user.refreshTokens=user.refreshTokens.filter(t=>t.jti!==d.jti); await user.save();}} return true};
exports.verifyEmail=async(email,code)=>{const user=await User.findOne({email:email.toLowerCase()}); if(!user||user.emailVerificationOtp!==code||user.emailVerificationExpires<new Date()) throw new AppError('Invalid OTP',400); user.isEmailVerified=true; user.emailVerificationOtp=undefined; await user.save(); return safeUser(user)};
exports.forgot=async(email)=>{const user=await User.findOne({email:email.toLowerCase()}); if(!user) return true; const code=otp(); user.resetPasswordOtp=code; user.resetPasswordExpires=new Date(Date.now()+10*60e3); await user.save(); await sendMail(user.email,'Reset Aligno password',`Your password reset OTP is ${code}`); return true};
exports.reset=async(email,code,password)=>{const user=await User.findOne({email:email.toLowerCase()}); if(!user||user.resetPasswordOtp!==code||user.resetPasswordExpires<new Date()) throw new AppError('Invalid OTP',400); user.password=password; user.resetPasswordOtp=undefined; await user.save(); return true};
async function sendMail(to,subject,text){try{await transporter().sendMail({from:process.env.MAIL_FROM,to,subject,text})}catch(e){if(process.env.NODE_ENV==='production') throw e}}
exports.safeUser=safeUser;
